// packages/components-react/src/Card/NieuwsCard.tsx
import { ForwardedRef, forwardRef, PropsWithChildren } from 'react';
import '@dronten/components-css/card/index.scss';

export interface NieuwsCardProps {
  imageUrl: string;
  linkUrl: string;
  title: string;
  description?: string;
  dateTime: string;
}

export const NieuwsCard = forwardRef(
  (
    { imageUrl, linkUrl, title, description, dateTime, ...restProps }: PropsWithChildren<NieuwsCardProps>,
    ref: ForwardedRef<HTMLDivElement>,
  ) => {
    return (
      <>
        <div ref={ref} className="dronten-nieuws-card" {...restProps}>
          <div className="dronten-nieuws-card__image">
            <img srcSet={imageUrl} alt="" />
          </div>

          <div className="dronten-nieuws-card__content">
            <h3 className="dronten-nieuws-card__title">
              <a href={linkUrl}>{title}</a>
            </h3>

            <time dateTime={Math.floor(new Date(dateTime).getTime() / 1000).toString()}>
              <i className="fal fa-clock"></i>
              {dateTime}
            </time>

            {description && <div className="dronten-nieuws-card__excerpt">{description}</div>}

            <a className="dronten-nieuws-card__button" href={linkUrl} tabIndex={-1}>
              Lees meer
              <i className="fa fa-chevron-right"></i>
            </a>
          </div>
        </div>
      </>
    );
  },
);

NieuwsCard.displayName = 'NieuwsCard';

// apps/poc-vue/src/components/design-system-components/NieuwsCard.vue
<script setup lang="ts">
defineProps<{
  imageUrl: string
  linkUrl: string
  title: string
  description?: string
  dateTime: string
}>()
</script>

<template>
  <div class="dronten-nieuws-card">
    <div class="dronten-nieuws-card__image">
      <img :srcset="imageUrl" alt="" />
    </div>

    <div class="dronten-nieuws-card__content">
      <h3 class="dronten-nieuws-card__title">
        <a :href="linkUrl">{{ title }}</a>
      </h3>

      <time :date-time="Math.floor(new Date(dateTime).getTime() / 1000).toString()">
        <i class="fal fa-clock"></i>
        {{ dateTime }}
      </time>

      <div v-if="description" class="dronten-nieuws-card__excerpt">{{ description }}</div>

      <a class="dronten-nieuws-card__button" :href="linkUrl" tab-index="-1">
        Lees meer
        <i class="fa fa-chevron-right"></i>
      </a>
    </div>
  </div>
</template>

<style src="@dronten/components-css/card/index.scss" />
